server:
  port: 8301
spring:
  boot:
    admin:
      client:
        url: http://${febs-monitor-admin}:8401
        username: febs
        password: 123456
        instance:
          prefer-ip: true

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: FEBS-Auth-Social
          uri: lb://FEBS-Auth
          predicates:
            - Path=/auth/social/**
          filters:
            - name: Hystrix
              args:
                name: socialfallback
                fallbackUri: forward:/fallback/FEBS-Auth
        - id: FEBS-Auth
          uri: lb://FEBS-Auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/FEBS-Auth
        - id: FEBS-Server-System
          uri: lb://FEBS-Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/FEBS-Server-System
        - id: FEBS-Server-test
          uri: lb://FEBS-Server-Test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: testfallback
                fallbackUri: forward:/fallback/FEBS-Server-Test
      loadbalancer:
        use404: true
      default-filters:
        - StripPrefix=1

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

    # 网关增强配置
    # data:
    #   mongodb:
    #     host: ${mongo.url}
    #     port: 27017
    #     database: febs_cloud_route

    # redis:
    #   database: 3
    #   host: ${redis.url}
    #   port: 6379
    #   lettuce:
    #     pool:
    #       min-idle: 8
    #       max-idle: 500
    #       max-active: 2000
    #       max-wait: 10000
    #   timeout: 5000


# 网关增强配置
febs:
  gateway:
    enhance: false
    jwt:
      secret: 123456
      expiration: 36000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    socialfallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eager-load:
    enabled: true

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway

